

services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9912134
      POSTGRES_DB: userdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
