curl -X GET http://localhost:8080/admin/dashboard -H 
"Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQxNjQ5MDAxLCJyb2xlIjoiYWRtaW4iLCJ1c2VySWQiOjF9.Uglt4HkV572e-2D0ItjV-Fynd9Sl4hoqPbk2teA2yxo"
